### ISSUE TITLE
(Bug) Getting error :the getter length on Danbooru

### ISSUE THREAD

**Issue by khalilpro1st** [NO-ob/LoliSnatcher_Droid#84]
![Screenshot_2022-01-11-02-14-03-153_com noaisu loliSnatcher](https://user-images.githubusercontent.com/43694921/148825217-361489d2-63fd-4ba0-87b3-6520247186c8.jpg)

Can use rating tag, but the other is getting this error massage length even when I don't use tag

**Comment by NANI-SORE** [comment]
Seems like they changed something in the api related to blocked/paywalled stuff.
For now you can add "-status:banned -status:deleted" to your searches to avoid that issue, until the fix is released.

Also, can you give what search query you used?

**Comment by khalilpro1st** [comment]
![Screenshot_2022-01-11-22-25-30-718_com noaisu loliSnatcher](https://user-images.githubusercontent.com/43694921/148971227-61ae0fc6-d2e6-46fe-838c-ccd30fb9d83a.jpg)
If only using that on search still get that on page#5
But using with other search query can bypass that
![Screenshot_2022-01-11-22-52-50-794_com noaisu loliSnatcher](https://user-images.githubusercontent.com/43694921/148976028-dc33a75b-4210-4321-a62f-fd07545da898.jpg)

**Comment by NANI-SORE** [comment]
That's just a temporary workaround to allow at least something to load, wait for the update to fix it completely.
Are you on github or store version?

(Please remove first screenshot, I'm not sure github allows nsfw stuff.)

**Comment by NANI-SORE** [comment]
Fix is out for github users
https://github.com/NO-ob/LoliSnatcher_Droid/releases/tag/2.1.5
